apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-list-generator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: test
        url: https://192.168.59.115:8443
      - cluster: prod
        url: https://192.168.59.116:8443
  template:
    metadata:
      name: '{{.cluster}}-app'
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/harsh2478/GitOps-Training.git
        targetRevision: HEAD
        path: 'multienv/{{.cluster}}'
      destination:
        server: '{{.url}}'
        namespace: default
