apiVersion: v1
kind: Secret
metadata:
  name: my-cluster2-add
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: my-cluster2
  server: https://192.168.59.105:8443 
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjRMWElLNXdnc2kxWndxMTM5UDBDUzdjZjJWUUJoeVNJcXcwMWhoNVN6WFEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzM0MDA4NTg4LCJpYXQiOjE3MzQwMDQ5ODgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImFyZ29jZC1wcm9kIiwidWlkIjoiNmQwNGQzMTEtOWY2YS00N2NjLWI1OTEtNDY3YTA0ZDlmMTNmIn19LCJuYmYiOjE3MzQwMDQ5ODgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmFyZ29jZC1wcm9kIn0.bMVt47fh1690uT9IX0TemzSOBoIeQO8PwEf8PvXMZH-84VJPRtpy_xd1bc8CXqzpxa-fWpjRezxEBiYL2w_eNYWCbLsLKfyMBnOXOAqNGZqmh8Fe1I3HjmLZ9hKljlTP3bhJTWEq-M9p6KCzQbHBt9CWTy6ZN-_XCW2NUyjceLZRf_79KyiNrlqcSgs7iEmxEO5q6_FBNqLyd1lzKVOSYmnu4WDvNfDqEEkE01MNzlVYRxQQcDW8QMVhAhkhL3ulcbDPn_szQBAKvFCkMjw1bd7OftycT_XAq4xOztG4D3YjpnM0stDWxCjsix1RGnbVcDTTlgTmr4ItvAYzseYJfg",
      "tlsClientConfig": {
          "insecure": true 
      }
    }
