apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-cluster-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://192.168.59.105:8443
    namespace: default
  source:
    repoURL: 'https://github.com/harsh2478/GitOps-Training.git'
    path: Production
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

