apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-1
  name: web-1
  namespace: default
spec:
  ports:
  - protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: web-1
  type: NodePort
status:
  loadBalancer: {}
