apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-1
    app.kubernetes.io/instance: production-application
  name: web-1
  namespace: default
spec:
  ports:
    - nodePort: 30000
      protocol: TCP
      targetPort: 80
  selector:
    app: web-1
  type: NodePort
status:
  loadBalancer: {}
